# -*- coding: utf-8 -*-
"""csvFile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRy81obAexTsh5OU_D_6JtmHQ7_4SjI5
"""

import csv

import matplotlib.pyplot as plt

with open('data.csv', 'r') as file:

  categories = []
  values = []

  reader = csv.reader(file)

  next(reader)

  for row in reader:
    categories.append(row[0])
    values.append(int(row[1]))

  print(categories)
  print(values)

  colors = ['#fc0f03','#03fc03','#3503fc', '#3705a3', 'k']

  plt.bar(categories, values, color=colors)

  plt.xlabel("Category")
  plt.ylabel("Value")

  plt.title("Fruit Distribution")

  plt.show()